<!DOCTYPE html>
<html>

<head>
    <title>Scheduled Transactions Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .text-success {
            color: #28a745;
        }

        .text-danger {
            color: #dc3545;
        }

        .header {
            margin-bottom: 20px;
        }

        .filters {
            margin-bottom: 15px;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Scheduled Transactions Report</h1>
        <div class="subtitle">Generated on {{ now()->format('Y-m-d H:i:s') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th width="3%">ID</th>
                <th>User</th>
                <th>Type</th>
                <th>Frequency</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Next Run</th>
                <th>Last Run</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($transactions as $transaction)
                @php $amount = json_decode($transaction->payload)->amount; @endphp
                <tr>
                    <td width="3%">{{ $transaction->id }}</td>
                    <td>{{ $transaction->user->name }}</td>
                    <td>{{ ucfirst($transaction->type) }}</td>
                    <td>{{ ucfirst($transaction->frequency) }}</td>
                    <td class="currency">{{ config('app.currency') }}{{ number_format($amount, 2) }}</td>
                    <td class="status-{{ strtolower($transaction->status) }}">{{ ucfirst($transaction->status) }}</td>
                    <td>{{ $transaction->next_run_at?->format('M d, Y H:i') }}</td>
                    <td>{{ $transaction->last_run_at?->format('M d, Y H:i') }}</td>
                    <td>{{ $transaction->created_at->format('M d, Y H:i') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Report generated by {{ config('app.name') }} &bull; Page 1 of 1
    </div>
</body>

</html>
